vich_uploader:
    db_driver: orm
    mappings:
        livre_image:
            uri_prefix: /images/livres
            upload_destination: '%kernel.project_dir%/public/images/livres'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
